# Generated by Django 5.1.2 on 2024-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_investmenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='transaction_type',
            field=models.CharField(default='Buy', max_length=20),
        ),
    ]
