# Generated by Django 5.1.2 on 2024-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
