# Generated by Django 5.1.2 on 2024-10-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wallet_transaction_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
