# Generated by Django 5.1.2 on 2024-10-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallet_transaction_history_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
