# Generated by Django 5.1.2 on 2024-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
