# Generated by Django 5.1.2 on 2024-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_savingsgoal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
